---
  - name: "Name Game"                       #Имя игры  
    hosts: ubuntu                           #Хост на котором необходимо выполнить задачи
    become: yes                             #Выполнить под суперпользователем

    roles:                                  #Список ролей для запуска
      - deploy_apache_web                   #Запускаемая роль
