---
- name: My Playbook
  hosts: all
  become: true

  vars:
    mytext: "Hello Igor"

  tasks:
    - name: Ping test
      ping:

    - include_tasks: create_folders.yaml
    - include_tasks: create_files.yaml